//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BallanceSum
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<System.Guid> SaleMan { get; set; }
        public Nullable<decimal> TotalBallance { get; set; }
        public Nullable<decimal> InputDailyAmount { get; set; }
    }
}
