//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceList
    {
        public System.Guid ID { get; set; }
        public string TabGroupAll { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> ItemID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
