//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleOrder()
        {
            this.SaleLines = new HashSet<SaleLine>();
        }
    
        public System.Guid SaleID { get; set; }
        public Nullable<System.Guid> CustAccount { get; set; }
        public Nullable<System.Guid> SalesMan { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string Description { get; set; }
        public string SaleStatus { get; set; }
        public string ShipTo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DeliTime { get; set; }
        public int LotId { get; set; }
        public string ShopName { get; set; }
        public string ShopPhone { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleLine> SaleLines { get; set; }
    }
}
