//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleLine
    {
        public System.Guid LotID { get; set; }
        public Nullable<System.Guid> SaleID { get; set; }
        public System.Guid LineNum { get; set; }
        public Nullable<System.Guid> ItemID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> LineAmount { get; set; }
        public string ItemName { get; set; }
        public string ItemColor { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual SaleOrder SaleOrder { get; set; }
    }
}
