//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public System.Guid UserID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public string Role { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
